/**
 * Filesystem-based crosswalk data loader (Karpathy Wiki Pattern).
 *
 * Reads pre-exported JSON from src/content/crosswalk/ - zero network calls.
 * Data is generated by scripts/export_crosswalk_data.py and copied at build
 * time via `npm run crosswalk:copy`.
 */
import fs from 'fs'
import path from 'path'
import type { ClassificationSystem, CrosswalkStat } from './types'

const DATA_DIR = path.join(process.cwd(), 'src', 'content', 'crosswalk')

let _systemsCache: ClassificationSystem[] | null = null
let _statsCache: CrosswalkStat[] | null = null

export function getStaticSystems(): ClassificationSystem[] {
  if (_systemsCache) return _systemsCache
  const filePath = path.join(DATA_DIR, 'systems.json')
  const raw = fs.readFileSync(filePath, 'utf-8')
  _systemsCache = JSON.parse(raw)
  return _systemsCache!
}

export function getStaticStats(): CrosswalkStat[] {
  if (_statsCache) return _statsCache
  const filePath = path.join(DATA_DIR, 'stats.json')
  const raw = fs.readFileSync(filePath, 'utf-8')
  _statsCache = JSON.parse(raw)
  return _statsCache!
}
