/**
 * Filesystem-based tree data loader (Karpathy Wiki Pattern).
 *
 * Reads pre-exported JSON from src/content/tree/ - zero network calls.
 * Data is generated by scripts/export_tree_data.py and copied at build
 * time via `npm run tree:copy`.
 *
 * Large systems (NDC 112K, LOINC 102K, ICD-10-CM 12K) are trimmed
 * server-side to keep the RSC payload small and the browser responsive.
 */
import fs from 'fs'
import path from 'path'

const DATA_DIR = path.join(process.cwd(), 'src', 'content', 'tree')

/**
 * Max nodes to send through the RSC prop. Systems with more nodes
 * get trimmed to fewer levels. Users can expand deeper via API.
 */
const MAX_PROP_NODES = 300

export interface TreeNodeData {
  code: string
  title: string
  level: number
  parent_code: string | null
  sector_code: string | null
  is_leaf: boolean
  children_count: number
}

const _cache = new Map<string, TreeNodeData[] | null>()

export function getStaticTree(systemId: string): TreeNodeData[] | null {
  if (_cache.has(systemId)) return _cache.get(systemId)!
  const filePath = path.join(DATA_DIR, `${systemId}.json`)
  if (!fs.existsSync(filePath)) {
    _cache.set(systemId, null)
    return null
  }
  const raw: TreeNodeData[] = JSON.parse(fs.readFileSync(filePath, 'utf-8'))

  // Trim large systems to keep the RSC prop payload small
  const data = raw.length > MAX_PROP_NODES ? trimToSafeDepth(raw) : raw

  _cache.set(systemId, data)
  return data
}

/**
 * Progressively remove deeper levels until the node count is
 * under MAX_PROP_NODES. Keeps parent-child relationships intact -
 * trimmed children become expandable "+" nodes in the UI.
 *
 * For flat systems (all nodes at level 1, no hierarchy), returns
 * null since a radial tree adds no value.
 */
function trimToSafeDepth(nodes: TreeNodeData[]): TreeNodeData[] | null {
  const levels = [...new Set(nodes.map((n) => n.level))].sort((a, b) => a - b)

  // Flat system (single level) with too many nodes - tree view adds no value
  if (levels.length === 1) return null

  // Try including levels one by one until we'd exceed the limit
  let result = nodes
  for (let i = levels.length - 1; i >= 1; i--) {
    const maxLevel = levels[i - 1]
    const trimmed = nodes.filter((n) => n.level <= maxLevel)
    result = trimmed
    if (trimmed.length <= MAX_PROP_NODES) break
  }

  // If even first level is too large, skip tree view
  if (result.length > MAX_PROP_NODES) return null

  return result
}
